.TH authup 8
.SH NAME
authup \- read an SMTP or POP3 username and password
.SH SYNOPSIS
.B authup
.I protocol
.I prog
.SH DESCRIPTION
.B authup
reads an SMTP or POP3 username and password from the network.
It then runs
.IR prog .

.B authup
is most commonly invoked from
.B tcpserver
or
.B sslserver
as

.EX
  reup -t 5     \\
  authup smtp   \\
  checkpassword \\
  checknotroot  \\
  fixsmtpio     \\
  env RELAYCLIENT="" ofmipd
.EE

or

.EX
  authup pop3   \\
  checkpassword \\
  checknotroot  \\
  qmail-pop3d
.EE

as root, so that
.B checkpassword
can run
.B qmail-smtpd
or
.B qmail-pop3d
under the UID of the authenticated user.

If
.B QMAILQUEUE
is set, the designated
.B qmail-queue
wrapper will also run as the authenticated user.
This can be useful for filtering.

.B authup
expects descriptor 0 to read from the network
and descriptor 1 to write to the network.
It reads a username and password from descriptor 0
in SMTP's AUTH LOGIN or AUTH PLAIN styles
or in POP3's USER-PASS style.
It invokes
.IR prog ,
with the same descriptors 0 and 1;
descriptor 2 writing to the network;
and descriptor 3 reading the username, a 0 byte, the password,
another 0 byte,
a protocol-specific datum such as a timestamp or challenge,
and a final 0 byte.
.B authup
then waits for
.I prog
to finish.
It prints an error message if
.I prog
crashes or exits nonzero.

.B authup
should be used only within
a secure network.
Otherwise an eavesdropper can steal passwords.
.SH "ENVIRONMENT VARIABLES"
The authenticated user is available to child processes as
.BR AUTHUSER .

If
.B BROKEN_SASL_AUTH_CLIENTS
is set,
.B authup
will advertise AUTH support in a non-standard way
to add interoperability with Outlook Express 4, Exchange 5,
and other SMTP clients that implement an obsolete version of the AUTH command.
.SH "CONTROL FILES"
.TP 5
.I smtpgreeting / pop3greeting
SMTP and POP3 greeting messages.
Default:
.IR me ,
if that is supplied;
otherwise
.B authup
will refuse to run.
The first word of the greeting
should be the current host's name.
.TP 5
.I timeoutsmtpd / timeoutpop3d
Number of seconds
.B authup
will wait for each new buffer of data from the remote SMTP or POP3 client.
Default: 1200.
.SH "COMPATIBILITY"
While
.B CRAM-MD5
is available in most SMTP AUTH patches, and
.B APOP
is available in
.BR qmail-popup ,
neither is currently supported by
.BR authup .
If you need them, please share your use case with the author.
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-acceptutils@schmonz.com>
.SH "SEE ALSO"
reup(8),
checknotroot(8),
fixsmtpio(8),
stunnel(8),
qmail-qfilter-ofmipd-queue(8),
pymsgauth-tag(1),
qmail-smtpd(8),
qmail-pop3d(8),
qmail-popup(8).
