.TH AUTHUP 8 2020-12-11
.SH NAME
authup \- offer SMTP or POP3 authentication
.SH SYNOPSIS
.B authup
[
.B \-t \fItries
]
.I protocol
.I checkpassword
.I prog
.SH DESCRIPTION
.B authup
speaks just enough SMTP (AUTH LOGIN or PLAIN)
or POP3 (USER-PASS)
to parse a username and password and pass them to
.IR checkpassword .
.B authup
is most commonly invoked as root so
.I checkpassword
can change to the UID of the authenticated user before running
.IR prog .
.P
Common combinations of 
.I protocol
and
.IR prog :
.TP 5
.B smtp
and
.B "checknotroot fixsmtpio ofmipd"
.TP 5
.B pop3
and
.B "checknotroot qmail-pop3d"
.P
.B authup
waits for
.I checkpassword
and
.I prog
to finish, and prints an error message if either of them crashes or exits nonzero.
.SH "OPTIONS"
.TP
.B \-t \fItries
Disconnect after
.I tries
failed authentication attempts.
Default: 5 for SMTP, 1 for POP3.
.SH "ENVIRONMENT VARIABLES"
When running under
.B "sslserver -n"
or
.BR "s6-ucspitlsd" ,
.B authup
can offer TLS.
Set
.B UCSPITLS
to the special value
.B !
to require that clients negotiate TLS before authenticating.
.P
If
.B DISABLETLS
is set, the presence and value of
.B UCSPITLS
will be ignored.
.P
If
.B AUTHUP_SASL_BROKEN_CLIENTS
is set,
.B authup
will additionally advertise AUTH support in a second, non-standard way
to interoperate with Outlook Express 4, Exchange 5,
and other SMTP clients that implement an obsolete version of the AUTH command.
.P
If authentication succeeds,
.IR prog 's
environment will contain the username in
.BR AUTHUP_USER .
.P
Since
.I prog
will run with the privileges of the authenticated user, so will
any
.B qmail-queue
wrapper configured as
.BR QMAILQUEUE .
This can be useful for user-controlled filtering.
.SH "CONTROL FILES"
.TP 5
.I smtpgreeting / pop3greeting
SMTP and POP3 greeting messages.
Default:
.IR me ,
if that is supplied;
otherwise
.B authup
will refuse to run.
The first word of the greeting
should be the current host's name.
.TP 5
.I smtpcapabilities / pop3capabilities
SMTP and POP3 capabilities (one per line) to advertise in
.I EHLO
and
.IR CAPA ,
respectively.
Default:
.IR none .
Without the needed file,
.B authup
will refuse to run.

Typical POP3 capabilities: TOP, UIDL. (Omit STLS and USER.)

Typical SMTP capabilities: PIPELINING, 8BITMIME. (Omit STARTTLS and AUTH.)

Correct values for your system depend on what
.I prog
offers.
For instance, to inspect your installed
.BR qmail-smtpd :

$ echo EHLO | qmail-smtpd \\
     | sed -e '1,2d' -e 's|^....||' | egrep -v '^(STARTTLS|AUTH)'

.B authup
will automatically advertise TLS support when run under
.B "sslserver -n"
or
.BR "s6-ucspitlsd" .
.TP 5
.I timeoutsmtpd / timeoutpop3d
Number of seconds
.B authup
will wait for each new buffer of data from the remote SMTP or POP3 client.
Default: 1200.
.SH "COMPATIBILITY"
While
.B CRAM-MD5
is available in most SMTP AUTH patches, and
.B APOP
is available in
.BR qmail-popup ,
neither is currently supported by
.BR authup .
Nor is authenticating with a client certificate.
If you rely on any of these, please share your use case with the author.
.SH "EXAMPLES"
See
.IR https://schmonz.com/qmail/acceptutils .
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-acceptutils@schmonz.com>
.SH "SEE ALSO"
checknotroot(8),
fixsmtpio(8),
sslserver(1),
s6-ucspitlsd,
ucspi-tls(2),
qmail-qfilter-queue(8),
ofmipd(8),
qmail-smtpd(8),
qmail-pop3d(8),
qmail-popup(8).
