.TH AUTHUP 8 2018-10-19
.SH NAME
authup \- offer SMTP or POP3 authentication
.SH SYNOPSIS
.B authup
.I protocol
.I prog
.SH DESCRIPTION
.B authup
speaks just enough SMTP or POP3
to read a username and password from the network.
It then runs
.IR prog .

.B authup
is most commonly invoked from
.B tcpserver
or
.B sslserver
as

.EX
  reup -t 5     \\
  authup smtp   \\
  checkpassword \\
  checknotroot  \\
  fixsmtpio     \\
  env RELAYCLIENT="" ofmipd
.EE

or

.EX
  authup pop3   \\
  checkpassword \\
  checknotroot  \\
  qmail-pop3d
.EE

as root, so that
.B checkpassword
can run
.B ofmipd
or
.B qmail-pop3d
under the UID of the authenticated user.

.B authup
speaks just enough SMTP to parse usernames and passwords
from AUTH LOGIN or AUTH PLAIN,
or just enough POP3 to understand USER-PASS.
It invokes
.I prog
via the checkpassword interface.
.B authup
then waits for
.I prog
to finish.
It prints an error message if
.I prog
crashes or exits nonzero.

.B authup
does not perform any encryption of its own.
For security, make it available over the network only by means of
another program that encrypts the network connection.
.SH "ENVIRONMENT VARIABLES"
The authenticated user is available to child processes as
.BR AUTHUP_USER .

If
.B AUTHUP_SASL_BROKEN_CLIENTS
is set,
.B authup
will advertise AUTH support in a second, non-standard way
to interoperate with Outlook Express 4, Exchange 5,
and other SMTP clients that implement an obsolete version of the AUTH command.

Because
.B ofmipd
(or
.BR qmail-smtpd )
runs as the authenticated user,
so does
.BR qmail-queue ,
as well as any custom
.B QMAILQUEUE
wrapper.
This can be useful for user-controlled filtering.
.SH "CONTROL FILES"
.TP 5
.I smtpgreeting / pop3greeting
SMTP and POP3 greeting messages.
Default:
.IR me ,
if that is supplied;
otherwise
.B authup
will refuse to run.
The first word of the greeting
should be the current host's name.
.TP 5
.I timeoutsmtpd / timeoutpop3d
Number of seconds
.B authup
will wait for each new buffer of data from the remote SMTP or POP3 client.
Default: 1200.
.SH "COMPATIBILITY"
While
.B CRAM-MD5
is available in most SMTP AUTH patches, and
.B APOP
is available in
.BR qmail-popup ,
neither is currently supported by
.BR authup .
If you need them, please share your use case with the author.
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-acceptutils@schmonz.com>
.SH "SEE ALSO"
reup(8),
checknotroot(8),
fixsmtpio(8),
stunnel(8),
qmail-qfilter-ofmipd-queue(8),
ofmipd(8),
qmail-pop3d(8),
qmail-popup(8).
