.TH checknotroot 8
.SH NAME
checknotroot \- refuse to run as UID 0
.SH SYNOPSIS
.B checknotroot
.I prog
.SH DESCRIPTION
.B checknotroot
ensures that another command can never be
run as UID 0.

.B checknotroot
is most commonly placed after
.B checkpassword
and before its remaining arguments to ensure that if someone guesses the
root password, they won't know they did.

.SH "EXIT CODES"
If run by UID 0,
.B checknotroot
exits 1.
Otherwise it exits with the same code as
.IR prog .
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-acceptutils@schmonz.com>
.SH "SEE ALSO"
checkpassword(8),
authup(8),
fixsmtpio(8).
