.TH dieifuid0 8
.SH NAME
dieifuid0 \- refuse to run as root
.SH SYNOPSIS
.B dieifuid0
.I prog
.SH DESCRIPTION
.B dieifuid0
is most commonly placed after
.B checkpassword
and before its remaining arguments
to ensure that

- No further commands run as root, and

- If someone guesses the root password, they won't know they did.

.SH "EXIT CODES"
If run by UID 0,
.B dieifuid0
exits 1.
Otherwise it exits with the same code as
.IR prog .
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-acceptutils@schmonz.com>
.SH "SEE ALSO"
checkpassword(8),
qmail-authup(8),
fixsmtpio(8).
