.TH fixsmtpio 8
.SH NAME
fixsmtpio \- filter SMTP I/O and exit status
.SH SYNOPSIS
.B fixsmtpio
.I prog
.SH DESCRIPTION
.B fixsmtpio
is an SMTP proxy.
It wraps a program like
.B ofmipd
or
.B qmail-smtpd
that reads from stdin,
writes to stdout,
and assumes it's responsible for the entire conversation.
When it's not -- typically because
.B qmail-authup
has already initiated an authenticated session --
.B fixsmtpio
can be configured to adjust exit codes, SMTP responses,
and occasionally even requests.
.B fixsmtpio
can also be used to modify a public SMTP service.

By default, inserting an unconfigured
.B fixsmtpio
into the command chain should not change any observable behavior.
If you observe otherwise, please report the bug.

In typical usage, the
.B "EXIT CODES"
section is more important than usual.
.SH "EXIT CODES"
.B checkpassword
exits 1 for incorrect passwords.
This happens to be the same code with which
.B ofmipd
and
.B qmail-smtpd
indicate any error condition whatsoever.
Since
.B qmail-authup
needs to distinguish authentication failures from other kinds,
it's important that
.B fixsmtpio
be configured to exit with unique codes for each condition.
See
.BR EXAMPLES .

.B fixsmtpio
exits 18 if its configuration file exists but fails to parse.
This, too, is as
.B qmail-authup
expects.

.SH "ENVIRONMENT VARIABLES"
Typical filter rules (see
.BR "CONTROL FILES" ,
below)
apply if and only if
.B AUTHUSER
is set.
.B qmail-authup
sets it.

.SH "CONTROL FILES"
[env]:event:[request-prepend]:response-line-glob:[exitcode][:response]
.TP 5
.I fixsmtpio
Filter rules in the above format.
Default: none.
Values may not contain ":", the field separator.

.I env
(optional)
is an environment variable that must be present for the rule to apply.
If empty, no environment variable is required.

.I event
(required)
is an SMTP verb (or "clienteof", "greeting", or "timeout")
for which requests, responses, or both are to be filtered.
This field is matched case-insensitively.

.I request-prepend
(optional)
is a string to be prepended to the request before it's seen by the server.
Since
.B NOOP
is an SMTP verb that servers accept and do nothing interesting with,
"NOOP" followed by a space prevents the server from taking unwanted action.
If empty, the request is sent as is.

.I response-line-glob
(required)
is an
.BR fnmatch(3) -style
glob pattern, with no special options set.
The rule applies to every matching line of the server response.

.I exitcode
(optional)
is a numeric code with which
.B fixsmtpio
is to immediately exit.
If empty, it exits when it normally would.
If no rules override it,
.B fixsmtpio
exits with the same code as
.IR prog .

.I response
(optional)
is a string that replaces every matching line of the server response.
If empty, matching lines are removed.

As a special case, if
.B response
is set to "&fixsmtpio",
the replacement string is computed by an internal routine for that event.
(If no such internal routine exists,
.B fixsmtpio
emits an error and exits.)
For
.BR HELP ,
in an attempt to direct support requests to
.BR AUTHOR ,
an internal routine can
prepend this program's home page.
Please enable it!
For "greeting",
.BR EHLO ,
.BR HELO ,
and
.BR QUIT ,
internal routines can include
.I smtpgreeting
in the response, just as
.B qmail-smtpd
already does.
These are therefore primarily useful with
.BR ofmipd .

As another special case, if
.B response
is "&leavesmtpio",
the response is sent as is.

Rules are applied in the order written. For instance, if two rules
match, the later rule modifies the response returned by the
earlier rule.
If multiple matching rules for an event set
.BR exitcode ,
the last one wins.

Not all rules (alone or in combination) make practical sense.
An earlier rule can cause a later one to start (or stop) matching.
Keep your configuration as simple as possible, and test it well.

.TP 5
.I smtpgreeting
SMTP greeting message.
Default:
.IR me ,
if that is supplied;
otherwise
.B fixsmtpio
will refuse to run.
The first word of
.I smtpgreeting
should be the current host's name.


.SH "EXAMPLES"
See
.IR https://schmonz.com/qmail/acceptutils/fixsmtpio.txt .

.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-acceptutils@schmonz.com>
.SH "SEE ALSO"
qmail-authup(8),
checkpassword(8),
checknotroot(8),
qmail-smtpd(8),
ofmipd(8),
fnmatch(3),
fixcrio(1),
spamdyke.
