.TH qmail-fixsmtpio 8
.SH NAME
qmail-fixsmtpio \- filter SMTP daemon I/O and exit status
.SH SYNOPSIS
.B qmail-fixsmtpio
.I prog
.SH DESCRIPTION
.B qmail-fixsmtpio
is an SMTP proxy.
It wraps a daemon (typically
.B ofmipd
or
.BR qmail-smtpd )
that expects descriptor 0 to read from the network
and descriptor 1 to write to the network, but
that might not have expected to run under something like
.BR qmail-authup .

.B qmail-fixsmtpio
is most commonly used with
.B qmail-authup
to accept submitted messages from authenticated users.
It can also be used to change the behavior of a public SMTP service.

By default,
.B qmail-fixsmtpio
should not change observable behavior.
If you observe that it does, please report the bug.
.SH "EXIT CODES"
On most any failure,
.B ofmipd
and
.B qmail-smtpd
exit 1, which is the same code
.B checkpassword
uses for incorrect passwords.
To communicate status back to
.BR qmail-authup ,
configure
.B qmail-fixsmtpio
to exit with unique codes for certain errors,
and with 0 otherwise.
See EXAMPLES.

.SH "ENVIRONMENT VARIABLES"
Most filter rules typically apply iff
.B AUTHUSER
is set.
.B qmail-authup
sets it.

.SH "CONTROL FILES"
[env]:event:[request-prepend]:response-line-glob:[exitcode][:response]
.TP 5
.I fixsmtpio
Filter rules in the above format.
Default: none.

Values may not contain ":", the field separator.

.B env
(optional)
is an environment variable that must be present for the rule to apply.
If empty, no environment variable is required.

.B event
(required)
is an SMTP verb (or "greeting" or "timeout") whose requests, responses,
or both are to be filtered.
This field is matched case-insensitively.

.B request-prepend
(optional)
is a string to be prepended to the request before it's seen by the server.
"NOOP " prevents the server from taking unwanted action.
If empty, the request is sent as is.

.B response-line-glob
(required)
is a glob pattern.
The rule applies to every matching line of the server response.

.B exitcode
(optional)
is a numeric code with which
.B qmail-fixsmtpio
is to immediately exit.
If empty, it exits when it normally would.
If no rules override it,
.B qmail-fixsmtpio
exits with the same code as
.IR prog .

.B response
(optional)
is a string that replaces every matching line of the server response.
If empty, matching lines are removed.
If
.I unset
(by leaving off the ":" after
.BR exitcode ),
the response is sent as is.

As a special case, if
.B response
is set to "&qmail-fixsmtpio",
the replacement string is computed by an internal routine for that event.
If no such routine exists, the response is sent as is.

.SH "EXAMPLES"
.EX
 # always prepend authutils link to HELP message
 :help::*::&qmail-fixsmtpio

 # if client closes the connection, tell qmail-authup to be happy
 AUTHUSER:clienteof::*:0

 # if server greets us unhappily, notify qmail-authup
 AUTHUSER:greeting::4*:14
 AUTHUSER:greeting::5*:15

 # if server times out, hide message (qmail-authup has its own)
 AUTHUSER:timeout::*:16:

 # if we've already authenticated, replace greeting
 AUTHUSER:greeting::2*::&qmail-fixsmtpio

 # don't advertise AUTH or STARTTLS
 AUTHUSER:ehlo::250?AUTH*::
 AUTHUSER:ehlo::250?STARTTLS::

 # don't allow AUTH or STARTTLS
 AUTHUSER:auth:NOOP :*::502 unimplemented (#5.5.1)
 AUTHUSER:starttls:NOOP :*::502 unimplemented (#5.5.1)
.EE

.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-authutils@schmonz.com>
.SH "SEE ALSO"
qmail-authup(8),
checkpassword(8),
checkpassword-rejectroot(8),
qmail-smtpd(8),
ofmipd(8),
fnmatch(3).
