.TH QMAIL-QFILTER-QUEUE 8 2023-05-25
.SH NAME
qmail-qfilter-queue \- run a sequence of pre-queue filters
.SH SYNOPSIS
.B qmail-qfilter-queue
.SH DESCRIPTION
.B qmail-qfilter-queue
runs an administrator-defined sequence of filters
before calling
.BR qmail-queue .
Filters will be run by
.B qmail-qfilter
and must adhere to that interface.
If any filter rejects, the message is rejected.
.PP
.B qmail-qfilter-queue
is most commonly invoked from
.B qmail-smtpd
and
.BR ofmipd ,
so that incoming and submitted messages are filtered before
entering the queue.
.SH "ENVIRONMENT VARIABLES"
To have
.B qmail-smtpd
and/or
.B ofmipd
invoke
.B qmail-qfilter-queue
in place of
.BR qmail-queue ,
set
.B QMAILQUEUE
to
.I /var/qmail/bin/qmail-qfilter-queue
in your
.BR tcpserver 's
tcprules (and rebuild the CDB).
.PP
To have
.B qmail-qfilter-queue
filter messages before they reach the queue, also set
.B QMAILQUEUEFILTERS
to the relevant control file (and rebuild the CDB).
.SH "CONTROL FILES"
.B qmail-qfilter-queue
expects a sequence of filter programs.
Typical values for
.BR QMAILQUEUEFILTERS :
.TP 5
.I control/smtpfilters
For incoming messages.
.TP 5
.I control/ofmipfilters
For submitted messages.
.P
Filter programs must be listed one per line,
with no arguments.
Changing the sequence takes effect immediately, no restart required.
If the control file is empty,
contains only comments,
or doesn't exist,
messages are passed to
.BR qmail-queue .
.SH "ERRORS"
Some typical SMTP error messages and their likely causes:
.TP 5
.I "451 mail server temporarily rejected message (#4.3.0)"
.B qmail-qfilter
is not installed in
.IR "$PATH" .
.TP 5
.I "451 qq internal bug (#4.3.0)"
The control file lists a program that doesn't exist
or otherwise can't be executed.
.SH "EXAMPLES"
See
.IR https://schmonz.com/software/rejectutils .
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-rejectutils@schmonz.com>
.SH "SEE ALSO"
qmail-queue(8),
qmail-qfilter(1),
qmail-smtpd(8),
ofmipd(8),
tcpserver(1),
qmail-qfilter-viruscan(8),
qmail-qfilter-addtlsheader(8).
