.TH QMAIL-RCPTCHECK-REALRCPTTO 8 2018-12-30
.SH NAME
qmail-rcptcheck-realrcptto \- realrcptto patch as standalone program
.SH SYNOPSIS
.B qmail-rcptcheck-realrcptto
.SH DESCRIPTION
.B qmail-rcptcheck-realrcptto
is Paul Jarc's realrcptto patch repackaged as a
.BR qmail-qfilter -compatible
program.
.SH "EXAMPLES"
See
.IR https://schmonz.com/qmail/rejectutils .
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-rejectutils@schmonz.com>
.SH HISTORY
Based on this code from Paul Jarc:
.PP
.I http://code.dogmap.org/qmail/#realrcptto
.SH "SEE ALSO"
qmail-qfilter(1).
