.TH qmail-qfilter-pymsgauth 8
.SH NAME
qmail-qfilter-pymsgauth \- invoke 
.B pymsgauth-tag
on submitted messages
.SH SYNOPSIS
.B qmail-qfilter-pymsgauth
.SH DESCRIPTION
.B qmail-qfilter-pymsgauth
is a
.B qmail-qfilter
program.
It filters the submitted message through
.B pymsgauth-tag
iff the submitting user has configured pymsgauth.

Note that
.B pymsgauth-tag
is not part of upstream pymsgauth, and requires the following patch:
https://schmonz.com/qmail/pymsgauth/

Note that with most SMTP AUTH configurations,
the submitting user is always
.BR qmaild .
For
.B pymsgauth-confirm
to do its automatic job,
.B pymsgauth-tag
needs to run as the authenticated user.
SMTP AUTH with acceptutils does this.
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-acceptutils@schmonz.com>
.SH "SEE ALSO"
pymsgauth,
qmail-qfilter(1),
authup(8),
fixsmtpio(8).
