.TH QMAIL-RCPTCHECK 8 2020-12-15
.SH NAME
qmail-rcptcheck \- run a sequence of sender/recipient checks
.SH SYNOPSIS
.B qmail-rcptcheck
.SH DESCRIPTION
.B qmail-rcptcheck
runs an administrator-defined sequence of programs
to check SMTP envelope senders and recipients.
Checks must adhere to the
.B RCPTCHECK
interface.
If any check rejects, the message is rejected.
.PP
.B qmail-rcptcheck
is most commonly invoked from
.B qmail-smtpd
patched with either
.B qmail-spp
or
.BR RCPTCHECK .
.SH "ENVIRONMENT VARIABLES"
To run under
.BR qmail-spp :
none needed.
.PP
To run under
.BR RCPTCHECK :
set
.B RCPTCHECK
to
.I /var/qmail/bin/qmail-rcptcheck
in your
.BR tcpserver 's
tcprules (and restart).
.PP
To perform checks, inspect these variables:
.TP 5
.I SENDER
Contains the envelope sender.
.TP 5
.I RECIPIENT
Contains the envelope recipient.
.SH "CONTROL FILES"
To run under
.BR qmail-spp :
add
.I /var/qmail/bin/qmail-rcptcheck
in the
.I [rcpt]
section of
.IR smtpplugins .
.PP
To run under
.BR RCPTCHECK :
none needed.
.PP
In either case, to control
.BR qmail-rcptcheck :
.TP 5
.I rcptchecks
Sequence of checks.
.P
RCPTCHECK-compatible programs must be listed one per line,
with no arguments.
Changing the sequence takes effect immediately (no restart required).
If the control file is empty,
contains only comments,
or doesn't exist,
messages are not rejected.
.P
To test your configuration, as
.IR root ,
in
.IR /var/qmail :
.P
# env SENDER=a RECIPIENT=b setuidgid qmaild qmail-rcptcheck; echo $?
.SH "EXIT CODES"
As defined by the
.B RCPTCHECK
interface,
.I 120
is reserved.
Recipient-checking programs should exit
.I 111
when unable to verify,
.I 100
to reject, or
any other non-reserved code to accept.
.SH COMPATIBILITY
.BR RCPTCHECK -compatible
programs can run unmodified under
.B qmail-spp
simply by running them from
.BR qmail-rcptcheck .
.SH "ERRORS"
Some typical SMTP errors and their likely causes:
.TP 5
.I "421 unable to execute recipient check (#4.3.0)"
The control file lists a program that doesn't exist
or otherwise can't be executed.
.SH "EXAMPLES"
See
.IR https://schmonz.com/qmail/rejectutils .
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-rejectutils@schmonz.com>
.SH HISTORY
Based on this code from Jay Soffian:
.PP
.I http://www.soffian.org/downloads/qmail/qmail-smtpd-doc.html
.SH "SEE ALSO"
qmail-rcptcheck-badrcptto(8),
qmail-rcptcheck-qregex(8),
qmail-rcptcheck-realrcptto(8),
qmail-smtpd(8).
.PP
.I http://qmail-spp.sourceforge.net/doc/
