.TH qmail-reup 8
.SH NAME
qmail-reup \- run a program repeatedly
.SH SYNOPSIS
.B qmail-reup
[
.B \-t \fItries
]
.I subprogram
.SH DESCRIPTION
.B qmail-reup
is most commonly used to invoke
.B qmail-authup
so that a user isn't disconnected immediately on the first authentication failure.

.B qmail-reup
prints an error message if
.I subprogram
crashes or can't be started.
.SH "EXIT CODES"
.B qmail-reup
stops retrying as soon as

-
.I subprogram
exits 0 (success), or

-
.I subprogram
exits 12 (permanent failure), or

-
.B qmail-reup
reaches its retry limit.

.B qmail-reup
then exits with the same code as
.IR subprogram .
.SH "ENVIRONMENT VARIABLES"
Child processes can see how many tries have been made in
.BR REUP .
.SH "OPTIONS"
.TP
.B \-t \fItries
Run
.B subprogram
no more than
.I tries
times.
Default: 0 (unlimited).
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-authutils@schmonz.com>
.SH "SEE ALSO"
qmail-authup(8),
qmail-fixsmtpio(8).
