.TH QMAIL-QFILTER-VIRUSCAN 8 2020-12-15
.SH NAME
qmail-qfilter-viruscan \- viruscan patch as standalone program
.SH SYNOPSIS
.B qmail-qfilter-viruscan
.SH DESCRIPTION
.B qmail-qfilter-viruscan
is Russ Nelson's viruscan patch repackaged as a
.BR qmail-qfilter -compatible
program.
.SH "CONTROL FILES"
.TP 5
.I signatures
For incoming messages.
.SH "EXAMPLES"
See
.IR https://schmonz.com/qmail/rejectutils .
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-rejectutils@schmonz.com>
.SH HISTORY
Based on this code from Russ Nelson:
.PP
.I http://qmailorg.schmonz.com/qmail-smtpd-viruscan-1.3.patch
.SH "SEE ALSO"
qmail-qfilter(1).
