.TH QMAIL-RCPTCHECK-BADRCPTTO 8 2023-05-25
.SH NAME
qmail-rcptcheck-badrcptto \- badrcptto patch as standalone program
.SH SYNOPSIS
.B qmail-rcptcheck-badrcptto
.SH DESCRIPTION
.B qmail-rcptcheck-badrcptto
is Ward Vandewege's badrcptto patch repackaged as a
.BR qmail-rcptcheck -compatible
program.
.SH "CONTROL FILES"
.TP 5
.I badrcptto
For incoming messages.
.SH "EXAMPLES"
See
.IR https://schmonz.com/software/rejectutils .
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-rejectutils@schmonz.com>
.SH HISTORY
Based on this code from Ward Vandewege:
.PP
.I http://patch.be/qmail/
.SH "SEE ALSO"
qmail-rcptcheck(8).
