.TH reup 8
.SH NAME
reup \- run a program repeatedly
.SH SYNOPSIS
.B reup
[
.B \-t \fItries
]
.I prog
.SH DESCRIPTION
.B reup
is most commonly used to invoke
.B authup
so that a user isn't disconnected immediately on the first authentication failure.

.B reup
prints an error message if
.I prog
crashes or can't be started.
.SH "EXIT CODES"
.B reup
stops retrying as soon as

-
.I prog
exits 0 (success), or

-
.I prog
exits 12 (permanent failure), or

-
.B reup
reaches its retry limit.

.B reup
then exits with the same code as
.IR prog .
.SH "ENVIRONMENT VARIABLES"
Child processes can see how many tries have been made in
.BR REUP .
.SH "OPTIONS"
.TP
.B \-t \fItries
Run
.B prog
no more than
.I tries
times.
Default: 0 (unlimited).
.SH "AUTHOR"
.B Amitai Schleier <schmonz-web-acceptutils@schmonz.com>
.SH "SEE ALSO"
authup(8),
fixsmtpio(8).
